version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    - 9090:9090
    - 5432:5432
    expose:
      - "8080"
      - "9990"
      - "5432"
    env_file:
      - ./wildfly-config/db-env
#    volumes:
#    - ./wildfly-config/script.sh:/opt/script.sh